### PR TITLE
Non-root nginx and add drone CI

### PR DESCRIPTION
**Pull request by vaijab**

### CODE REVIEW

**Review by jaykeshur — APPROVED** [review]

**Comment by marcinc** [comment]
LGTM

**Comment by vaijab** [comment]
Just found a little issue, fixing it now.

**Comment by vaijab** [comment]
> Just found a little issue, fixing it now.

Fixed.

@Joseph-Irving / @lewismarshall  you should take a look at this change, because you will need this for making nginx-proxy run as non-root.

**Comment by stefancocora** [comment]
lgtm

**Comment by Joseph-Irving** [comment]
lgtm

**Pull request merged**
